- index.md
Add mentions of previous ATP Products, fix typo
> Add "ATPs" and fix Typos

- index.md
> Fix Message Header Analyzer

- index.md
I didn't know this admin center existed until today.
> Add Microsoft Stream's Admin Center

- index.md
> Add Tenant Availability Check website.

- about.md
Hey Adam,
Really nicely done BTW. Kudos to you and all who've contributed.
> Corrected some typos

- index.md
https://portal.azure.com/#blade/Microsoft_Azure_DataProtection/BackupCenterMenuBlade/overview
> add Azure Backup Center

- index.md
> Added Desktop Analytics

- index.md
Added https://resources.azure.com/raw to the list
> Added resources.azure.com/raw

- index.md
- userportals.md
https://twitter.com/alanjmcf/status/1331482659126730754?s=20
https://www.microsoft.com/en-gb/microsoft-365/business/mileage-tracking-software
> Add MileIQ as discussed on twitter

- userportals.md
The emoji doesn’t work in the webpage. (Was fine in markdown preview.)
> Remove attempted car emoji in MikeIQ

- _includes/nomatches.html
- _includes/quickfilter.html
- _layouts/default.html
- assets/css/style.scss
Added a "quick search" function
Gif demo: https://i.imgur.com/JrR6kQo.gif
> Quicksearch

- assets/css/style.scss
Added simple [row highlighting on hover](https://imgur.com/a/lPXXkG7)
> added row highlighting on hover

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.md
Setup Issue templates for bug report, feature requests, and support to help with anyone offering feedback or having problems
> Setup Issue templates for Bug Report and Feature Requests

- README.md
Update [front ReadMe](https://github.com/adamfowlerit/msportals.xyz/) to have a basic welcome, and directions toward contributing.
> Create front Readme

- _includes/quickfilter.html
Fixes https://github.com/adamfowlerit/msportals.io/issues/72
> Patch scrolling fix

- _data/portals/admin.json
For Microsoft Endpoint Manager Admin Console portal: https://aka.ms/memac
> Add MEMAC aka.ms link

- _data/portals/admin.json
https://github.com/adamfowlerit/msportals.io/issues/71
> Add link to status pages #71

- _data/portals/admin.json
Updated admin.json as https://portal.msrc.microsoft.com/en-us/engage/cars (was Current) now redirects to https://msrc.microsoft.com/report/abuse (was Preview)
> Submit Abuse Report - old Preview is now Current

- _data/portals/admin.json
Added [Azure Sentinel](https://azure.microsoft.com/en-au/services/azure-sentinel/) Blade Link to Subportals
> added Azure sentinel link

- _data/portals/admin.json
Added the link for Microsoft Intune for Education portal.
> added Intune for Education portal link

- _includes/quickfilter.html
> Fix for issue #111

- _data/portals/thirdparty.json
I noticed that MSShells.net is missing link to the repo
> Add repo of MSShells.net

- _data/portals/admin.json
Added link to create a New Organization (New Azure Active Directory) - https://account.azure.com/organization
> Added portal to create a New Azure Active Directory

- _data/portals/admin.json
Incusion of acronyms and notes for easy filtering. Acronyms often used by Microsoft.
> Added acronyms and notes commonly used

- _data/portals/admin.json
Please update the shortlinks to reflect the new naming of ATP products and more
> Updated short links

- _data/portals/admin.json
Reverts adamfowlerit/msportals.io#128
> Revert "Updated short links"

- _data/portals/admin.json
Added:
https://myapplications.microsoft.com/
https://myaccess.microsoft.com/
https://www.microsoftazurepass.com/
> Added Azure Pass, My Apps, My Access

- _data/portals/admin.json
#141 Changing private preview to Public preview for lighthouse per my issue
> Updated Microsoft 365 Lighthouse note to Public Preview

- _data/portals/admin.json
Updated system names to the new ones - hopefully the old names are still searchable.
> New names of services

- _data/portals/admin.json
- _data/portals/user.json
The following no longer exist in the admin JSON:
Name|Url
-|-
Customer Digital Experiences|http://demos.microsoft.com
Outlook OAuth Sandbox|https://oauthplay.azurewebsites.net
PowerApps Unified Interface Transition Portal|https://runone.powerappsportals.com
Windows Insider Lab for Enterprise|https://olympia.windows.com
Skype Preview / Microsoft Teams Preview|https://www.skypepreview.com
The following no longer exist in the user JSON:
Name|Url
-|-
Dynamics 365|https://home.dynamics.com
> Removed a number of broken links

- _data/portals/admin.json
Adding Speech Studio and Language Studio portals URLs (Cognitive Services portals)
> Adding Speech Studio and Language Studio portals

- _data/portals/admin.json
Add aka.ms/rca to Microsoft Remote Connectivity Analyzer
> Add aka.ms/rca

- _data/portals/admin.json
Power Platform admin center missing aka.ms shortlink #177 - per @pebroz
> adding https://aka.ms/ppacd

- _data/portals/admin.json
Added Microsoft Purview on line #104
Issue #180
> Added Microsoft Purview

- _data/portals/user.json
Added Device Login for "Work or School Account" or "Microsoft account or MSA"
> Added Device Logins

- _data/portals/us-govt.json
Power Automate Maker Portal - https://make.gov.powerapps.us/ for GCC Moderate
> Added Power Automate Maker Portal

- _data/portals/us-govt.json
Correct 186/187 PR for Microsoft Power Automate End User and Power Automate Maker Portal
> Correct Changes

- _data/portals/admin.json
Added Developer Portal for Teams
[dev.teams.microsoft.com](https://dev.teams.microsoft.com/)
MS docs: [teams-developer-portal](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/teams-developer-portal)
> Added Developer Portal for Teams

- _data/portals/user.json
Added Power Pages under userportals
[make.powerpages.microsoft.com](https://make.powerpages.microsoft.com)
Power Pages docs: [here](https://docs.microsoft.com/en-us/power-pages/)
> Added Power Pages

- _data/portals/admin.json
Microsoft has just released a new portal for their identity portfolio
> Addition of Microsofts new Entra portal

- _data/portals/admin.json
> Added the AKA for Graph

- _data/portals/us-govt.json
Added the Entra portal for GCC and GCC High (https://entra.microsoft.us).
> Added Entra portal

- _data/portals/us-govt.json
Remove [Duplicate] Power Platform is listed twice for GCC High - #216
> Remove [Duplicate] Power Platform

- _data/portals/user.json
> Fix little mistake (remove space in url)

- _data/portals/admin.json
- Update Azure DevOps to the actual portal, and add B2B link
- Add the M365 Developer Program Dashboard
- Add the Redeem Invite B2B link
> Add more B2B links

- _data/portals/thirdparty.json
I'm not sure about this change, just a proposal :
- Delete the portal (because we are already on it at this moment...)
- Sort by portalname, more aesthetic and practical.
> Alphabetical sorting and deletion of the portal

- _data/portals/admin.json
Updated links as per MS Doco.
https://github.com/microsoft/aka/blob/main/README.md
| Portal | Old shortcut | New shortcut |
|--------|--------|--------|
| Intune | MEMAC | IN |
| Power Platform | PPACD | PPAC |
| AzureAD | NA | AZAD |
| Defender | NA | DE | 
Should be able to close out this issue - https://github.com/adamfowlerit/msportals.io/issues/212
> Add & Update Shortcuts

- _data/portals/user.json
See : https://azure.microsoft.com/en-us/blog/introducing-microsoft-fabric-data-analytics-for-the-era-of-ai/
> Add "Fabric"

- _data/portals/admin.json
> Update : Power BI Playground

- _data/portals/thirdparty.json
Just a suggestion, similar to msportals.io _(but for documentation mainly, not portal)_ but I find it handy for someone who wants information specifically about the Intune product.
> Suggestion : IntuneMaps

- _data/portals/admin.json
Added missing comma in admin.json to fix syntax error
> Add missing comma in admin.json

- _data/portals/admin.json
More info: https://learn.microsoft.com/en-us/security-copilot/?view=o365-worldwide
> Security Copilot added

- _data/portals/user.json
> Add : Bing Chat Enterprise

- _data/portals/readme.md
Update readme.md:
- add training.json
- align markdown table header
> Update readme.md - add training.json

- _data/portals/licensing.json
Because we don't all live in australia ! 😄 
(It's more dynamic)
> Update licensing.json - Fix Australia link

- _data/portals/admin.json
> add Entra, Purview B2B links

- assets/css/style.scss
resolves #94 - preview available at https://jlaundry.github.io/msportals.io/
> Add Light colour theme

- _data/portals/training.json
> Fix ms900 course link

- _data/portals/thirdparty.json
Usefull Tool from merill.net (thank you)
> Add akasearch.net

- _data/portals/user.json
Adding https://portal.sdg.teams.microsoft.com or https://aka.ms/siplogin
> Added Device Login - SIP Login

- _data/portals/admin.json
Azure IoT Central - Not so new but still in use.
> Azure IoT Central

- _data/portals/thirdparty.json
Added https://www.samsungknox.com/
> Added Samsung Knox 3rd party

- 3rdparty.md
- 404.md
- _includes/quickfilter.html
- _layouts/default.html
- about.md
- favorites.md
- index.md
- licensing.md
- training.md
- userportals.md
- usgovt.md
> Make quick filter explicit on each page

- _data/portals/user.json
Just a refresh, and i think it is more clean to keep only "1 line" for SSPR portal
> Update all SSPR portal

- _data/portals/user.json
See : https://www.microsoft.com/en/microsoft-places
> Add Microsoft Places

- _data/portals/user.json
Forgot about the aka.ms link... 😄
> Add aka.ms/places

- _data/portals/user.json
Just discovered this url by accident... Thanks @BohrenAn
https://blog.icewolf.ch/archive/2022/06/25/microsoft-teams-voicemail-settings-for-users-and-admins/
> Added : Microsoft PSTN user settings

- _data/portals/us-govt.json
Adding the Power BI Admin Portal URL for GCC Moderate.
> Add Power BI Admin Portal to us-govt.json

- _data/portals/admin.json
Portal provides billing and usage information for Azure Offer of ms-azr-0036p. View the balance of credit remaining and other usage information.
> Added Azure Sponsorships portal

- _data/portals/admin.json
- _data/portals/thirdparty.json
Added a link to the Microsoft Certification Hub 
Renamed WDAC Wizard to App Control Policy Wizard
Removed an extra comma to fix admin.json
> Add new portal, Rename App Control Wizard

- _data/portals/user.json
Hey 
"https://www.office.com/launch/forms" doesn't seem to work properly
Fixed !
> Update user.json - Forms
